---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver_config:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]

        
suites:
  - name: default
    run_list:
      - recipe[chef-cd-workshop::default]
    attributes:
